#cask 'docker-toolbox'
#cask 'docker'
#sudo hungry first
cask 'virtualbox'

cask 'atom'
cask '1password'
cask 'google-chrome'

cask 'cinch'
cask 'caffeine'
cask 'spectacle'
cask 'flux'

brew 'gpg'
brew 'heroku'
brew 'watch'
brew 'htop'
brew 'gh'
brew 'duti'
brew 'dockutil'

cask 'franz'
cask 'evernote'
cask 'skitch'
cask 'vlc'
cask 'telegram'
cask 'alfred'
cask 'disk-inventory-x'
cask 'flowdock'
cask 'skype'
cask 'spotify'
cask 'carbon-copy-cloner'
cask 'launchrocket'
cask 'tunnelblick'
cask 'sourcetree'
cask 'p4merge'
